(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(button ((((supports :underline t)) (:box (:line-width 2 :color "gray" :style released-button)))))
 '(escape-glyph ((((background dark)) (:foreground "gray30"))))
 '(flymake-errline ((((class color)) (:underline "red"))))
 '(flymake-warnline ((((class color)) (:underline "lightblue"))))
 '(ido-only-match ((((class color)) (:foreground "Green"))))
 '(ido-subdir ((((min-colors 88) (class color)) (:foreground "orange1"))))
 '(italic ((((supports :underline t)) (:underline "gray"))))
 '(link ((((class color) (min-colors 88) (background dark)) (:foreground "cyan1"))))
 '(magit-item-highlight ((((class color) (background dark)) (:background "#112"))))
 '(mode-line-inactive ((t (:background "black" :foreground "wheat"))))
 '(mumamo-background-chunk-major ((((class color) (min-colors 88) (background dark)) nil)))
 '(mumamo-background-chunk-submode ((((class color) (min-colors 88) (background dark)) nil)))
 '(p4-depot-added-face ((t (:foreground "lightblue"))))
 '(p4-depot-deleted-face ((t (:foreground "orange"))))
 '(p4-diff-del-face ((t (:foreground "orange"))))
 '(p4-diff-file-face ((t nil)))
 '(p4-diff-head-face ((t nil)))
 '(p4-diff-ins-face ((t (:foreground "lightblue"))))
 '(persp-selected-face ((t (:foreground "red" :weight bold))))
 '(rcirc-server ((((class color) (min-colors 88) (background dark)) (:foreground "gray50"))))
 '(region ((t (:background "DarkOliveGreen"))))
 '(trailing-whitespace ((((class color) (background dark)) nil))))

(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(Buffer-menu-buffer+size-width 46)
 '(blink-cursor-delay 0.0)
 '(blink-cursor-interval 0.2)
 '(coffee-tab-width 2)
 '(compilation-scroll-output t)
 '(confirm-kill-emacs (quote yes-or-no-p))
 '(display-time-24hr-format t)
 '(eshell-buffer-name "*eshell*")
 '(eshell-output-filter-functions nil)
 '(eshell-send-direct-to-subprocesses t)
 '(eudc-protocol (quote ldap))
 '(eudc-server "ldap")
 '(gdb-enable-debug t)
 '(gnus-fetch-old-headers (quote some))
 '(gnus-inhibit-mime-unbuttonizing nil)
 '(gnus-summary-line-format "%U%R %d %*%5L%I %(%z%[%-23,23n%]%) %s
")
 '(gud-gdb-command-name "gdb --annotate=1")
 '(gud-tooltip-echo-area nil)
 '(gud-tooltip-mode t)
 '(icicle-reminder-prompt-flag nil)
 '(ido-default-buffer-method (quote selected-window))
 '(ido-default-file-method (quote selected-window))
 '(ido-enable-flex-matching t)
 '(ido-use-faces nil)
 '(inferior-lisp-program "sbcl")
 '(js-indent-level 2)
 '(large-file-warning-threshold nil)
 '(max-lisp-eval-depth 1500)
 '(max-specpdl-size 12040)
 '(mumamo-background-chunk-major (quote default))
 '(mumamo-background-chunk-submode (quote default))
 '(mumamo-chunk-coloring (quote no-chunks-colored))
 '(mumamo-set-major-mode-delay -1)
 '(ns-command-modifier (quote meta))
 '(org-export-pdf-remove-logfiles t)
 '(org-startup-folded (quote showeverything))
 '(p4-user-email "")
 '(pivotal-api-token "d51db1d51c1eda993f2988061185f3b6")
 '(python-indent 3)
 '(rails-tags-command "/opt/local/bin/ctags -e -a --Ruby-kinds=-f -o %s -R %s")
 '(rcirc-default-nick "chopmo")
 '(rcirc-default-user-full-name "Jacob Poulsgaard Tjoernholm")
 '(rcirc-default-user-name "chopmo")
 '(rcirc-startup-channels-alist (quote (("^irc.freenode.net$" "#clojure"))))
 '(remember-data-file "~/Dropbox/org/notes.org")
 '(rspec-spec-command "~/.rbenv/shims/rspec")
 '(rspec-use-bundler-when-possible nil)
 '(rspec-use-rake-flag nil)
 '(ruby-electric-expand-delimiters-list nil)
 '(safe-local-variable-values (quote ((require-final-newline) (ruby-compilation-executable . "ruby") (ruby-compilation-executable . "ruby1.8") (ruby-compilation-executable . "ruby1.9") (ruby-compilation-executable . "rbx") (ruby-compilation-executable . "jruby") (folded-file . t))))
 '(scss-compile-at-save nil)
 '(scss-sass-command "/usr/bin/sass")
 '(shell-file-name "/bin/sh")
 '(speedbar-use-images t)
 '(tags-revert-without-query t)
 '(warning-suppress-types (quote ((\(undo\ discard-info\)))))
 '(weblogger-config-alist (quote (("chopmo" "http://chopmo.wordpress.com/xmlrpc.php" "chopmo" "" "5186267") ("default" ("user" . "chopmo") ("server-url" . "http://chopmo.wordpress.com/xmlrpc.php") ("weblog" . "5186267")))))
 '(weblogger-server-password "")
 '(yari-ri-program-name "ri"))



