;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cljr-slash
        coffee-dedent-line-backspace
        complete-symbol
        end-of-buffer
        indent-for-tab-command
        isearch-exit
        isearch-forward-regexp
        isearch-printing-char
        kill-region
        paredit-backward-kill-word
        paredit-doublequote
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-open-round
        paredit-splice-sexp
        paredit-wrap-round
        ))

(setq mc/cmds-to-run-once
      '(
        helm-M-x
        markdown-outdent-or-delete
        ))
